error: Remove backticks in `Error:new` doc comment
The term "message" in the comments refers to a concept, not a param
name, so it shouldn't be enclosed in backticks.